/**
 * GENERATED by `npm run lotus:assets` from `measureLotusFrames()` — do not edit.
 * `tests/unit/scripts/app/lotus-assets.test.ts` re-measures and fails on drift.
 */
import type { LotusFrames } from '@/components/app/ui/lotus-draw';

export const LOTUS_FRAMES: LotusFrames = {
  animated: {
    tight: { box: [-113.31, -122.42, 228.6, 163.37], bloomFraction: 0.973753280839895 },
    water: { box: [-144.97, -122.42, 290.97, 163.37], bloomFraction: 0.7650273224043715 },
  },
  still: {
    tight: { box: [-113.31, -91.96, 228.6, 132.91], bloomFraction: 0.973753280839895 },
    water: { box: [-144.97, -91.96, 290.97, 132.91], bloomFraction: 0.7650273224043715 },
    glyph: { box: [-83.07, -119.69, 173.4, 129.94], bloomFraction: 0.9653979238754326 },
  },
};
