/**
 * App declarations for the CI and test gates.
 *
 * **Fork-owned scaffold** — Sunrise ships both lists empty and does NOT change
 * this file after release, so your edits here merge cleanly on upgrade (the
 * stable contract is this file's exports, not their values).
 *
 * ---------------------------------------------------------------------------
 * DAYBREAK: this is a BRIDGE. Your leaf's entries go in `lib/app/leaf-ci.ts`.
 * ---------------------------------------------------------------------------
 * Sunrise's seam is built for two tiers and hands "the fork" one file. Daybreak
 * is the middle of three, so this file is a surface Daybreak would otherwise
 * keep empty for its own forks. Instead it declares the **framework** tier's
 * entries and spreads the reserved **leaf** lists after them — the CI analogue
 * of the boot bridge (`bootstrap.ts` → `leaf-bootstrap.ts`), the nav bridge, the
 * export bridge and the drift bridge. Both lists are append-shaped, so the tiers
 * compose; nothing here overrides anything a leaf declares.
 *
 * If you are building a leaf app on Daybreak: **do not edit this file.** Every
 * example below applies to you unchanged — put your entries in
 * `lib/app/leaf-ci.ts` and they land in exactly the same core lists.
 *
 * Auto-wired in two places: `vitest.config.ts` spreads
 * {@link appCoverageExclusions} into `coverage.exclude`, and
 * `scripts/ci/scoped-tests.ts` spreads {@link appAlwaysRunTests} into
 * `ALWAYS_RUN_TESTS`, which `npm run test:changed` and `/pre-pr` union into
 * every scoped run.
 *
 * ## Why this exists
 *
 * Both platform lists are *core* registries with core guards over them, and
 * neither had anywhere for a fork to put its own entry. A fork that added one
 * `tsx` CLI script and one whole-tree test had to edit three Sunrise-owned
 * files it had never touched (#759) — `vitest.config.ts`,
 * `scripts/ci/missing-tests.ts` and `scripts/ci/scoped-tests.ts` — to declare
 * artefacts that were entirely its own. Each is a cheap "keep mine" on merge,
 * but it is a conflict on three files that had none, and every fork with a
 * script of its own meets it.
 *
 * Declaring here keeps the core lists — and the guards that hold them
 * accurate — exactly as they are for core entries, while your entries stay
 * yours.
 *
 * Boundary-clean: the only import is the sibling `lib/app/leaf-ci.ts` (types and
 * two empty arrays, itself importing nothing), so this stays within the
 * `lib/app/**` framework-agnostic boundary and can still be read by a vite
 * config, a `tsx` script and a test alike. Upstream's version imports nothing at
 * all — the difference is Daybreak's bridge, and it deliberately does NOT reach
 * into `@/lib/framework`, which would drag the framework into `vitest.config.ts`
 * at config-load time.
 *
 * Full guide: CUSTOMIZATION.md §4 · .context/testing/scoped-runs.md
 */

// RELATIVE, and it has to be — the same constraint that makes `vitest.config.ts`
// import THIS file as `./lib/app/ci`. The `@/` alias is defined by
// `vitest.config.ts` for the test runtime; vite does not apply it while loading
// the config, and this module is loaded by that config, so a `@/` specifier here
// fails to resolve before any alias exists. Verified, not assumed: with `@/` the
// whole suite dies at startup with `Cannot find module '@/lib/app/leaf-ci'`.
// eslint-disable-next-line @typescript-eslint/no-restricted-imports -- see above; the @/ alias does not exist at vitest config-load time.
import { leafCoverageExclusions, leafAlwaysRunTests } from './leaf-ci';

/** One path the coverage reporter should not have an opinion about. */
export interface AppCoverageExclusion {
  /**
   * The pattern, exactly as vitest's `coverage.exclude` takes it (picomatch).
   *
   * Note that `coverage.exclude` does NOT honour `!`-negated entries, so a
   * re-include has to be expressed inside the pattern — the extglob
   * `scripts/smoke/!(*-assertions).ts` upstream is the worked example.
   */
  pattern: string;
  /**
   * Why coverage cannot see it — concrete, in the terms the next person needs.
   *
   * "Structurally 0%" is not a reason on its own; *"a standalone `tsx` entry
   * point nothing imports, so vitest never executes it"* is. A required field
   * rather than a comment, so the decision travels with the entry instead of
   * living in a diff.
   */
  reason: string;
}

/**
 * Coverage exclusions this fork adds to Sunrise's own.
 *
 * The case this is for: a **standalone CLI entry point** — `main()` at module
 * scope, `process.exit()`, nothing importing it. It is absent from a full
 * coverage run altogether and only materialises at 0% when a scoped run forces
 * it in, i.e. the first time anyone edits it, where the per-file 80% floor then
 * fails on a file no test could ever have covered.
 *
 * **Exclude the file, not the directory it sits in.** Naming the wrapper is
 * almost always right: one CLI entry point, one line, and everything beside it
 * stays gated whatever it is called.
 *
 * **The directory form has one carve-out and it is spelled, not implied.**
 * `scripts/smoke/!(*-assertions).ts` excludes the whole directory *except*
 * files named `*-assertions.ts`, which is upstream's convention for the pure
 * logic a harness extracts to be testable. It spares that and nothing else — a
 * sibling called `lib.ts`, `helpers.ts` or anything else is excluded along with
 * the wrapper, tests or no tests. So reach for it only if your extracted half
 * follows that naming; otherwise the pattern silently un-gates the code you
 * separated out in order to test it, which is the opposite of what extracting
 * it was for. (Coverage `exclude` honours no `!`-negated ENTRY, which is why
 * the carve-out has to live inside the pattern.)
 *
 * **What an entry here does NOT do.** `/pre-pr` step 4f
 * (`npm run check:missing-tests`) still asks whether an excluded file should
 * have a test, exactly as it does for every core exclusion. That check reports
 * and never gates, so the answer is given in review rather than silenced here.
 *
 * @example
 * ```ts
 * export const appCoverageExclusions: AppCoverageExclusion[] = [
 *   {
 *     // The wrapper by name. `scripts/boundary/!(*-assertions).ts` would have
 *     // taken `lib.ts` with it — the tested half — because that split is
 *     // `check.ts`/`lib.ts`, not the `*-assertions.ts` naming the carve-out
 *     // keys on.
 *     pattern: 'scripts/boundary/check.ts',
 *     reason:
 *       'a tsx CLI run by `npm run framework:boundary` in the lint job — ' +
 *       'filesystem and ESLint I/O that nothing imports. Its pure logic lives ' +
 *       'in scripts/boundary/lib.ts, which stays gated and has its own tests.',
 *   },
 * ];
 * ```
 */
export const appCoverageExclusions: AppCoverageExclusion[] = [
  {
    // The wrapper BY NAME, not `scripts/boundary/!(*-assertions).ts`. That
    // extglob would take `lib.ts` with it — the tested half — because this split
    // is `check.ts`/`lib.ts`, not the `*-assertions.ts` naming the carve-out
    // keys on. Verified against picomatch, and it is why upstream's example says
    // so (Sunrise #762).
    pattern: 'scripts/boundary/check.ts',
    reason:
      'a `tsx` CLI entry point run by `npm run framework:boundary` in the lint job — ' +
      '`main()` at module scope doing filesystem and ESLint I/O, which nothing imports, ' +
      'so a full coverage run never executes it and a scoped run forces it in at 0%. Its ' +
      'pure logic lives in `scripts/boundary/lib.ts`, which stays gated and has its own tests.',
  },
  // The leaf tier's own exclusions (reserved-empty in Daybreak).
  ...leafCoverageExclusions,
];

/** One test that must run regardless of what the module graph says. */
export interface AppAlwaysRunTest {
  /**
   * Repo-relative path, forward slashes. Must exist — a typo fails the guard.
   *
   * It does not have to live under `tests/`: a colocated
   * `lib/billing/boot-order.test.ts` is fine, as is `.spec.ts`, matching what
   * the selection side already collects. What it must be is a test file the
   * runner can hand to `vitest` as an argument, in a directory
   * `vitest.config.ts` collects — `tests/e2e/**` is excluded there, so a spec
   * declared inside it would exist, pass every other check, and never run.
   *
   * (The example is deliberately not `lib/framework/…`. That tier is reserved
   * and `tests/unit/reserved-fork-tiers.test.ts` holds it empty unless the
   * checkout declares it in `lib/app/reserved-tiers.ts` — a second decision,
   * and not one this seam should walk you into by example.)
   */
  path: string;
  /**
   * What tree state it reads, i.e. why no import chain reaches it.
   *
   * Keep it concrete: "reads the tree" is not a reason, *"reads
   * `prisma/seeds/` off disk and nothing imports a seed file"* is. The reason
   * is what tells the next person whether their new test belongs here.
   */
  reason: string;
}

/**
 * Whole-tree tests this fork adds to Sunrise's own always-run list.
 *
 * The case this is for: a test whose **subject is the repository**, not a
 * module — it globs a directory, parses a schema, greps for a call site, or
 * runs a tool over the tree. `vitest --changed` selects by import graph, and no
 * import chain reaches a test like that, so the change it exists to catch is
 * precisely the change that will not select it.
 *
 * **A scoped run is a pre-flight, not the last gate.** CI's `test-full` job runs
 * the whole suite on every PR while `CI_TEST_SCOPE` is `full` (the default), so
 * a list one entry short costs a local run that misses something CI then
 * catches. On a fork that sets `CI_TEST_SCOPE=changed` that net has a hole —
 * see `.context/testing/scoped-runs.md`.
 *
 * @example
 * ```ts
 * export const appAlwaysRunTests: AppAlwaysRunTest[] = [
 *   {
 *     path: 'tests/unit/prisma/seeds/framework-boot-order.test.ts',
 *     reason:
 *       'reads `prisma/seeds/` off disk to hold `_framework/` sorting after the core ' +
 *       'seeds and before any leaf directory. Nothing imports a seed file, and a rename ' +
 *       'errors nowhere — a leaf seed just stops finding its rows.',
 *   },
 * ];
 * ```
 */
export const appAlwaysRunTests: AppAlwaysRunTest[] = [
  {
    path: 'tests/unit/prisma/framework-boot-seed.test.ts',
    reason:
      'reads `prisma/seeds/` off disk to assert the framework boot seed still sorts after ' +
      'the core seeds and before any leaf directory. Nothing imports a seed file, so adding ' +
      'or renaming one — the change that breaks the ordering, silently — reaches this test ' +
      'by no import chain.',
  },
  // The leaf tier's own whole-tree tests (reserved-empty in Daybreak).
  ...leafAlwaysRunTests,
];
